require "rake"
require "rake/clean"
require "rake/gempackagetask"

include FileUtils

NAME = "gil"
GILVERSION = "0.1.1"

CLEAN.include "pkg"

spec = Gem::Specification.new do |s|
  s.name         = NAME
  s.version      = GILVERSION
  s.platform     = Gem::Platform::RUBY
  s.author       = "Simon Jefford"
  s.email        = "simon.jefford@gmail.com"
  s.homepage     = "http://sjjdev.com"
  s.summary      = "Gil. What have you resolved today?"
  s.bindir       = "bin"
  s.description  = s.summary
  s.executables  = %w( gil )
  s.require_path = "lib"
  s.files        = %w( LICENSE Rakefile ) + Dir["{bin,lib}/**/*"]

  # Dependencies
  s.add_dependency "activeresource"
  s.add_dependency "rake"
  s.add_dependency "rspec"

  s.rubyforge_project = 'gil'
end

Rake::GemPackageTask.new(spec) do |package|
  package.gem_spec = spec
end

desc "Run :package and install the resulting .gem"
task :install => :package do
  sh %{sudo gem install --local pkg/#{NAME}-#{GILVERSION}.gem --no-rdoc --no-ri}
end
